# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 */7 * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: SamirPaul1
          template: classic
          base: activity, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_display: large
          config_octicon: yes
          config_timezone: Asia/Calcutta
          plugin_languages: yes
          plugin_languages_analysis_timeout: 25
          plugin_languages_analysis_timeout_repositories: 25
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, lines
          plugin_languages_ignored: html, css
          plugin_languages_indepth: yes
          plugin_languages_limit: 15
          plugin_languages_other: yes
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_sections: base
          # plugin_traffic: yes
          repositories_forks: yes
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
